config/routes.rb
Rails.application.routes.draw do
  match '/*all' => 'application#cors_preflight_check', :via => [:OPTIONS]
  resources :pins

end

app/models/pin.rb
# == Schema Information
#
# Table name: pins
#
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  name       :string
#  pin_pi     :integer
#  updated_at :datetime         not null
#  value      :boolean          default(FALSE)
#

class Pin < ActiveRecord::Base
  after_save :set_value

  def exec_cmd(cmd)
    begin
      logger.debug "EXECUTING => #{cmd}"
      return system(cmd)
    rescue E => e
      puts e
    end

    false
  end

  def up_device
    unless File.exist?("/sys/class/gpio/gpio#{pin_pi}")
      if File.exist?('/sys/class/gpio/export')
        exec_cmd("echo #{pin_pi} > /sys/class/gpio/export")
      end
    end
  end

  def set_value
    logger.debug "START => Set value: pin#{pin_pi} = #{value};"
    up_device

    if File.exist?("/sys/class/gpio/gpio#{pin_pi}/direction")
      if value
        exec_cmd("echo out > /sys/class/gpio/gpio#{pin_pi}/direction")
      else
        exec_cmd("echo in > /sys/class/gpio/gpio#{pin_pi}/direction")
      end
    end

    logger.debug "END => Set value: pin#{pin_pi} = #{value};"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  def cors_preflight_check
    render :nothing => true, :status => 200
  end
end

app/controllers/pins_controller.rb
# PinsController class
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:name, :pin_pi, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rupibox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<%= semantic_form_for @pin do |f| %>
  <%= f.semantic_errors %>

  <%= f.inputs do %>
      <%= f.input :name %>
      <%= f.input :pin_pi %>

      <%= f.input :value %>
  <% end %>

  <%= f.actions do %>
      <%= f.action :submit, :as => :button, :button_html => {:class => 'btn btn-primary btn-update'} %>
  <% end %>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pin pi</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.name %></td>
        <td><%= pin.pin_pi %></td>
        <td><%= pin.value %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pin.name %>
</p>

<p>
  <strong>Pin pi:</strong>
  <%= @pin.pin_pi %>
</p>

<p>
  <strong>Value:</strong>
  <%= @pin.value %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>